CREATE TABLE customer (
  CUS_ID INT PRIMARY KEY,
  CUS_NAME VARCHAR(20) NOT NULL,
  CUS_PHONE VARCHAR(10) NOT NULL,
  CUS_CITY VARCHAR(30) NOT NULL,
  CUS_GENDER CHAR
);
INSERT INTO customer (CUS_ID, CUS_NAME, CUS_PHONE, CUS_CITY, CUS_GENDER)
VALUES
  (1, 'AAKASH', '9999999999', 'DELHI', 'M'),
  (2, 'AMAN', '9785463215', 'NOIDA', 'M'),
  (3, 'NEHA', '9999999999', 'MUMBAI', 'F'),
  (4, 'MEGHA', '9994562399', 'KOLKATA', 'F'),
  (5, 'PULKIT', '7895999999', 'LUCKNOW', 'M');
SELECT CUS_GENDER, COUNT(DISTINCT CUS_ID) AS Total_Customers
FROM order_table
JOIN customer ON order_table.CUS_ID = customer.CUS_ID
WHERE ORD_AMOUNT >= 3000
GROUP BY CUS_GENDER;
SELECT CUS_GENDER, COUNT(DISTINCT CUS_ID) AS Total_customers
FROM customer
INNER JOIN order_table ON customer.CUS_ID = order_table.CUS_ID
WHERE ORD_AMOUNT >= 3000
GROUP BY CUS_GENDER;

